name: fab_scroll_animator
description: Add native Flutter animation to the FloatingActionButton when scrolling a ListView or GridView.
version: 1.0.0
repository: https://github.com/chrystoffer/fab_scroll_animator
homepage: https://github.com/chrystoffer/fab_scroll_animator
issue_tracker: https://github.com/seu-chrystoffer/fab_scroll_animator/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

topics:
  - scroll
  - animator
  - fab
  - floatingactionbutton